In [49]:
from qutip import *
from numpy import sqrt, pi, cos, sin, exp, array, real, imag, linspace, zeros
from numpy import math
factorial = math.factorial
import matplotlib.pyplot as plt
%matplotlib inline

In [59]:
N = 2

In [61]:
def phaseshifter(phi):
    """ I believe this shifts one arm by phi 
    doesn't seem to be working though"""
    shifter = tensor(exp(1j*phi)*identity(N),Qobj(zeros([N,N])))
    return shifter

In [62]:
def stateplot(state):
    plt.plot(real(state.full()),"bo")
    plt.plot(imag(state.full()),"ro")

In [63]:
phaseshifter(pi/4)

TypeError: 'coo_matrix' object is not subscriptable

Quantum object: dims = [[2, 2], [2, 2]], shape = [4, 4], type = oper, isherm = True
Qobj data =
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]

In [60]:
zeros([N,N])

array([[ 0.,  0.],
       [ 0.,  0.]])